general {
    lock_cmd = hyprlock
}

# Lock after 5 minutes of inactivity
listener {
    timeout = 300
    on-timeout = hyprlock
}

# Always lock before suspend
listener {
    on-before-sleep = hyprlock
}
