 exec-once = nm-applet &
 exec-once = waybar &
 exec-once = swww-daemon &
 exec-once = hypridle &
 exec-once = mako
 exec-once = ~/.config/hypr/scripts/waybar_peek.py
 exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
