# Refer to https://wiki.hypr.land/Configuring/Variables/
general {
    gaps_in = 1
    gaps_out = 5

    border_size = 0

    col.active_border = rgba(33ccffee) rgba(00ff99ee) 90deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.8

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 5
        passes = 3
 	    ignore_opacity = true
    	new_optimizations = true
    	special = false
    	popups = true
    	xray = true
	
        vibrancy = 0.1696
    }
}

animations {
  enabled = yes

  bezier = myBezier, 0.05, 0.9, 0.1, 1.05
  bezier = been, 0.24, 0.9, 0.25, 0.91
  # bezier = been2, 0,.94,.5,.99
  bezier = menu_decel, 0.1, 1, 0, 1
  #  bezier = linear, 0.0, 0.0, 1.0, 1.0
  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = slow, 0, 0.85, 0.3, 1
  bezier = overshot, 0.7, 0.6, 0.1, 1.1
  bezier = bounce, 1.1, 1.6, 0.1, 0.85
  bezier = sligshot, 1, -1, 0.15, 1.25
  bezier = nice, 0, 6.9, 0.5, -4.20
  
  animation = windowsIn, 1, 5, slow, popin
  animation = windowsOut, 1, 7, been, popin 70%
  animation = windowsMove, 1, 5, wind, slide
  animation = border, 1, 1, linear
  animation = fade, 1, 5, overshot
  animation = workspaces, 1, 5, wind
  animation = windows, 1, 5, bounce, popin
}


input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    accel_profile=flat
    follow_mouse=1
    force_no_accel=1

    touchpad {
        natural_scroll = true
    }
}

#############################
### ENVIRONMENT VARIABLES ###
#############################
# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct
